In [3]:
!pip install xgboost
!pip install folium

In [4]:
import pandas as pd
from matplotlib import pyplot as plt 
import seaborn as snsㅎ
import numpy as np
import folium 

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [ ]:
lscp_pop_and_bike = pd.read_csv('/content/drive/My Drive/Compas/compas/csv 파일 여기로!/bikepoint_lscp_all_300.csv')
lscp_pop_and_bike

좌표     대여수  ...  Hosu_yes  Park_count
0      (37.59052639593674, 126.88041634904563)     0.0  ...         0           0
1     (37.590546726423185, 126.88154829019997)     0.0  ...         0           0
2      (37.59142713034578, 126.88039079257342)     0.0  ...         0           0
3      (37.59144746148929, 126.88152274735107)     0.0  ...         0           0
4      (37.59146778178655, 126.88265470326604)     0.0  ...         0           0
...                                        ...     ...  ...       ...         ...
3229   (37.70445091519225, 126.75467703178417)  6093.0  ...         0           1
3230  (37.704472506609626, 126.75581060819373)  6093.0  ...         0           1
3231    (37.70466633943072, 126.7660128502553)   473.0  ...         0           0
3232   (37.70468782197291, 126.76714643873707)   473.0  ...         0           0
3233   (37.70470929362739, 126.76828002842278)   473.0  ...         0           0

[3234 rows x 18 columns]

In [ ]:
Bike_Station=pd.read_csv('/content/drive/My Drive/Compas/compas/SBJ_2007_001/02.자전거스테이션.csv')
Bike_Station

Station_ID          STATION_NAME  거치대 수량         위도          경도
0           101          어울림마을 701동 앞      20  37.654775  126.834584
1           103          대림e-편한세상106동      20  37.660442  126.840377
2           104               탄현마을8단지      25  37.698523  126.766042
3           105             KT 덕양지사 앞      20  37.655244  126.839261
4           106           원당역 앞 공영주차장      30  37.653410  126.842530
..          ...                   ...     ...        ...         ...
159         350  ★하이파크5단지 502동앞 버스정류장      20  37.697867  126.753089
160         351          ◆일산에듀포레 푸르지오      40  37.702259  126.767231
161         352            ◆꿈에그린203동앞      40  37.666425  126.749244
162         353            ◆꿈에그린106동앞      40  37.666720  126.750784
163         992                ★피프틴센터       4  37.637529  126.833760

[164 rows x 5 columns]

In [ ]:
center = (37.647972, 126.835398)
zoom = 13

m = folium.Map(location=center, zoom_start=zoom, tiles='Stamen Toner')

for index, row in Bike_Station.iterrows():
    folium.Marker([row['위도'], row['경도']]).add_to(m)   
for index, row in lscp_pop_and_bike.iterrows():  
    folium.Circle([row['위도'], row['경도']],
                  radius = 3, color = 'red' ).add_to(m)
m

Output hidden; open in https://colab.research.google.com to view.

## 전처리

In [ ]:
lscp_pop_and_bike['스테이션'][0]

['155']

In [ ]:
from tqdm.notebook import tqdm
lscp_pop_and_bike['DN_avg'] = np.zeros(len(lscp_pop_and_bike))
lscp_pop_and_bike['Road_yes'] = np.zeros(len(lscp_pop_and_bike))
lscp_pop_and_bike['Space_count'] = np.zeros(len(lscp_pop_and_bike))
lscp_pop_and_bike['Culture_count'] = np.zeros(len(lscp_pop_and_bike))
lscp_pop_and_bike['Sport_count'] = np.zeros(len(lscp_pop_and_bike))
lscp_pop_and_bike['KINTEX'] = np.zeros(len(lscp_pop_and_bike))
lscp_pop_and_bike['Hosu_yes'] = np.zeros(len(lscp_pop_and_bike))
lscp_pop_and_bike['Park_count'] = np.zeros(len(lscp_pop_and_bike))


for i in tqdm(range(len(lscp_pop_and_bike))):
  for j in range(len(lscp_bike_300)):
    if str(lscp_bike_300['Bike_Station'].iloc[j]) in lscp_pop_and_bike['스테이션'].iloc[i]:
      lscp_pop_and_bike['DN_avg'].iloc[i] += lscp_bike_300['DN_avg'].iloc[j]
      lscp_pop_and_bike['Road_yes'].iloc[i] += lscp_bike_300['Road_yes'].iloc[j]
      lscp_pop_and_bike['Space_count'].iloc[i] += lscp_bike_300['Space_count'].iloc[j]
      lscp_pop_and_bike['Culture_count'].iloc[i] += lscp_bike_300['Culture_count'].iloc[j]
      lscp_pop_and_bike['Sport_count'].iloc[i] += lscp_bike_300['Sport_count'].iloc[j]
      lscp_pop_and_bike['KINTEX'].iloc[i] += lscp_bike_300['KINTEX'].iloc[j]
      lscp_pop_and_bike['Hosu_yes'].iloc[i] += lscp_bike_300['Hosu_yes'].iloc[j]
      lscp_pop_and_bike['Park_count'].iloc[i] += lscp_bike_300['Park_count'].iloc[j]

/usr/local/lib/python3.6/dist-packages/pandas/core/indexing.py:671: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer(indexer, value)


In [ ]:
lscp_pop_and_bike

좌표     대여수  ...  Hosu_yes  Park_count
0      (37.59052639593674, 126.88041634904563)     0.0  ...       0.0         0.0
1     (37.590546726423185, 126.88154829019997)     0.0  ...       0.0         0.0
2      (37.59142713034578, 126.88039079257342)     0.0  ...       0.0         0.0
3      (37.59144746148929, 126.88152274735107)     0.0  ...       0.0         0.0
4      (37.59146778178655, 126.88265470326604)     0.0  ...       0.0         0.0
...                                        ...     ...  ...       ...         ...
3229   (37.70445091519225, 126.75467703178417)  6093.0  ...       0.0         1.0
3230  (37.704472506609626, 126.75581060819373)  6093.0  ...       0.0         1.0
3231    (37.70466633943072, 126.7660128502553)   473.0  ...       0.0         0.0
3232   (37.70468782197291, 126.76714643873707)   473.0  ...       0.0         0.0
3233   (37.70470929362739, 126.76828002842278)   473.0  ...       0.0         0.0

[3234 rows x 17 columns]

In [ ]:
print(lscp_pop_and_bike['DN_avg'].unique())
print(lscp_pop_and_bike['Road_yes'].unique())
print(lscp_pop_and_bike['Space_count'].unique())
print(lscp_pop_and_bike['Culture_count'].unique())
print(lscp_pop_and_bike['Sport_count'].unique())
print(lscp_pop_and_bike['KINTEX'].unique())
print(lscp_pop_and_bike['Hosu_yes'].unique())
print(lscp_pop_and_bike['Park_count'].unique())

[ 22.  28.  60.  32.  50.  37.  11.  17.  26.  13.  15.  36.  31.  29.
  21.  52.  16.  42.  27.  14.  40.  20.  19.  55.  39.  46.  61.  12.
  41.  95.  73.  69.  53.  34.  18.  49.  75.  25.  67.  54.  86.  59.
   9.  45.  10.  43.  47.  30.  38.  24.  48.  44.  63.  33.  23.  35.
  77.  68.   8.   7.  90.  81. 127.  78. 118.  58.  65.  51.  76.  64.
 113.  85.  62.  57.  92.  84.  79.  82.  66.  96. 101. 130.  72. 107.]
[1. 0. 2. 3. 4. 5. 6.]
[   0.  293.  670.  377.  441.  461.   84.   64.  525.  148.   59.   99.
   95.   11.   35.  130.   46.   57.   22.  562. 1124. 1686. 1809. 2371.
 3056. 3179. 1932. 1370.  123. 1247. 2617. 2055.  808.  685.  413. 1493.
  660.  247. 1373.  713. 1354. 2067. 1707. 1013. 2514. 2101. 2154.  300.
  941. 1388.  694. 1141. 1460.  747.  447.   27.  125.  294.  185.  419.
  349.  643.   54.  768.  268.  214.  656. 1075.  482.  702.  488.   31.
   25. 1048. 1322.   56. 1108. 1163. 1783.  620.  949. 1569.  512. 1552.
 1115.  282.  248.  760.  603.  135.  2

In [ ]:
replacer = lambda x: 1.0 if x > 0 else 0.0
lscp_pop_and_bike['Road_yes']= lscp_pop_and_bike['Road_yes'].map(replacer)
lscp_pop_and_bike['Hosu_yes']= lscp_pop_and_bike['Hosu_yes'].map(replacer)
lscp_pop_and_bike['KINTEX']= lscp_pop_and_bike['KINTEX'].map(replacer)

In [ ]:
print(lscp_pop_and_bike['DN_avg'].unique())
print(lscp_pop_and_bike['Road_yes'].unique())
print(lscp_pop_and_bike['Space_count'].unique())
print(lscp_pop_and_bike['Culture_count'].unique())
print(lscp_pop_and_bike['Sport_count'].unique())
print(lscp_pop_and_bike['KINTEX'].unique())
print(lscp_pop_and_bike['Hosu_yes'].unique())
print(lscp_pop_and_bike['Park_count'].unique())

[ 22.  28.  60.  32.  50.  37.  11.  17.  26.  13.  15.  36.  31.  29.
  21.  52.  16.  42.  27.  14.  40.  20.  19.  55.  39.  46.  61.  12.
  41.  95.  73.  69.  53.  34.  18.  49.  75.  25.  67.  54.  86.  59.
   9.  45.  10.  43.  47.  30.  38.  24.  48.  44.  63.  33.  23.  35.
  77.  68.   8.   7.  90.  81. 127.  78. 118.  58.  65.  51.  76.  64.
 113.  85.  62.  57.  92.  84.  79.  82.  66.  96. 101. 130.  72. 107.]
[1. 0.]
[   0.  293.  670.  377.  441.  461.   84.   64.  525.  148.   59.   99.
   95.   11.   35.  130.   46.   57.   22.  562. 1124. 1686. 1809. 2371.
 3056. 3179. 1932. 1370.  123. 1247. 2617. 2055.  808.  685.  413. 1493.
  660.  247. 1373.  713. 1354. 2067. 1707. 1013. 2514. 2101. 2154.  300.
  941. 1388.  694. 1141. 1460.  747.  447.   27.  125.  294.  185.  419.
  349.  643.   54.  768.  268.  214.  656. 1075.  482.  702.  488.   31.
   25. 1048. 1322.   56. 1108. 1163. 1783.  620.  949. 1569.  512. 1552.
 1115.  282.  248.  760.  603.  135.  270.  427.  179.

In [ ]:
lscp_bike_300 = lscp_bike_300.astype({'Bike_Station': np.object})

In [ ]:
lscp_pop_and_bike['스테이션']

0       [155]
1       [155]
2       [155]
3       [155]
4       [155]
        ...  
3229    [346]
3230    [346]
3231    [351]
3232    [351]
3233    [351]
Name: 스테이션, Length: 3234, dtype: object

In [ ]:
lscp_pop_and_bike.columns

Index(['좌표', '대여수', '반납수', '총 이용횟수', '스테이션', '주거인구', '버스_승하차수', '지하철_승하차수',
       '유동인구', 'DN_avg', 'Road_yes', 'Space_count', 'Culture_count',
       'Sport_count', 'KINTEX', 'Hosu_yes', 'Park_count'],
      dtype='object')

# 1. 인구로만 모델링

In [ ]:
y = lscp_pop_and_bike[['총 이용횟수']]
X = lscp_pop_and_bike[['주거인구', '버스_승하차수', '지하철_승하차수','유동인구']]

X.shape, y.shape

((3234, 4), (3234, 1))

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 42, test_size = 0.1)

X_train.shape, X_test.shape, y_train.shape

((2910, 4), (324, 4), (2910, 1))

## 수치형 스케일링

In [ ]:
numerical_columns = ['주거인구', '버스_승하차수', '지하철_승하차수','유동인구']

In [ ]:
from sklearn.preprocessing import StandardScaler
std_scaler = StandardScaler()

In [ ]:
std_scaler.fit(X_train[numerical_columns])

StandardScaler(copy=True, with_mean=True, with_std=True)

In [ ]:
std_scaler.transform(X_train[numerical_columns])
std_scaler.transform(X_test[numerical_columns])

array([[ 0.78594449, -0.71582524, -0.33583384, -0.35147632],
       [-0.05063649, -0.28870097, -0.33583384, -0.33746457],
       [ 0.18896449, -0.52494794, -0.33583384, -0.34521462],
       ...,
       [ 0.18515753,  1.62514181, -0.33583384, -0.27468126],
       [-0.085613  , -0.51069125, -0.33583384, -0.34474693],
       [-1.37236782, -0.59580792, -0.33583384, -0.34753917]])

## 범주형 전처리

## 모델링 

In [ ]:
import xgboost as xgb

xgb_model = xgb.XGBRegressor(n_estimators=500, 
                              learning_rate = 0.1, 
                              max_depth = 3, objective = 'reg:squarederror').fit(X_train, y_train)

In [ ]:
xgb_model

XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=1, gamma=0,
             importance_type='gain', learning_rate=0.1, max_delta_step=0,
             max_depth=3, min_child_weight=1, missing=None, n_estimators=500,
             n_jobs=1, nthread=None, objective='reg:squarederror',
             random_state=0, reg_alpha=0, reg_lambda=1, scale_pos_weight=1,
             seed=None, silent=None, subsample=1, verbosity=1)

In [ ]:
print('train score : {}'.format(xgb_model.score(X_train, y_train)))
print('test score : {}'.format(xgb_model.score(X_test, y_test)))

train score : 0.7085184543113099
test score : 0.5418177854471633


In [ ]:
np.argsort(xgb_model.feature_importances_)

array([0, 3, 1, 2])

In [ ]:
feature_important = [ X_train.columns[i] for i in np.argsort(xgb_model.feature_importances_)[::-1]]
feature_important

['지하철_승하차수', '버스_승하차수', '유동인구', '주거인구']

# 2. Column들 추가해서 넣어보기 

In [ ]:
y = lscp_pop_and_bike[['총 이용횟수']]
X = lscp_pop_and_bike[['주거인구', '버스_승하차수', '지하철_승하차수','유동인구', 'DN_avg', 'Road_yes', 'Space_count', 'Culture_count',
       'Sport_count', 'KINTEX', 'Hosu_yes', 'Park_count']]

X.shape, y.shape

((3234, 12), (3234, 1))

In [ ]:
numerical_columns = ['주거인구', '버스_승하차수', '지하철_승하차수','유동인구',  'DN_avg', 'Space_count', 'Culture_count',
       'Sport_count', 'Park_count']

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 42, test_size = 0.1)

X_train.shape, X_test.shape, y_train.shape

((2910, 12), (324, 12), (2910, 1))

In [ ]:
from sklearn.preprocessing import StandardScaler
std_scaler = StandardScaler()

std_scaler.fit(X_train[numerical_columns])

std_scaler.transform(X_train[numerical_columns])
std_scaler.transform(X_test[numerical_columns])

array([[ 0.78594449, -0.71582524, -0.33583384, -0.35147632],
       [-0.05063649, -0.28870097, -0.33583384, -0.33746457],
       [ 0.18896449, -0.52494794, -0.33583384, -0.34521462],
       ...,
       [ 0.18515753,  1.62514181, -0.33583384, -0.27468126],
       [-0.085613  , -0.51069125, -0.33583384, -0.34474693],
       [-1.37236782, -0.59580792, -0.33583384, -0.34753917]])

In [ ]:
import xgboost as xgb

xgb_model = xgb.XGBRegressor(n_estimators=500, 
                              learning_rate = 0.1, 
                              max_depth = 3, objective = 'reg:squarederror').fit(X_train, y_train)

In [ ]:
print('train score : {}'.format(xgb_model.score(X_train, y_train)))
print('test score : {}'.format(xgb_model.score(X_test, y_test)))

train score : 0.9385801033497263
test score : 0.9048367299578098


In [ ]:
np.argsort(xgb_model.feature_importances_)

array([ 9,  8,  0,  3,  1,  4,  6, 11,  5,  7,  2, 10])

In [ ]:
feature_important = [ X_train.columns[i] for i in np.argsort(xgb_model.feature_importances_)[::-1]]
feature_important

['Hosu_yes',
 '지하철_승하차수',
 'Culture_count',
 'Road_yes',
 'Park_count',
 'Space_count',
 'DN_avg',
 '버스_승하차수',
 '유동인구',
 '주거인구',
 'Sport_count',
 'KINTEX']

# 3. 좌표 LSCP Renew

좌표 normalize

x = cos(lat) * cos(lon)  
y = cos(lat) * sin(lon)  
z = sin(lat) 

In [ ]:
lscp_pop_and_bike

좌표     대여수  ...  Hosu_yes  Park_count
0      (37.59052639593674, 126.88041634904563)     0.0  ...         0           0
1     (37.590546726423185, 126.88154829019997)     0.0  ...         0           0
2      (37.59142713034578, 126.88039079257342)     0.0  ...         0           0
3      (37.59144746148929, 126.88152274735107)     0.0  ...         0           0
4      (37.59146778178655, 126.88265470326604)     0.0  ...         0           0
...                                        ...     ...  ...       ...         ...
3229   (37.70445091519225, 126.75467703178417)  6093.0  ...         0           1
3230  (37.704472506609626, 126.75581060819373)  6093.0  ...         0           1
3231    (37.70466633943072, 126.7660128502553)   473.0  ...         0           0
3232   (37.70468782197291, 126.76714643873707)   473.0  ...         0           0
3233   (37.70470929362739, 126.76828002842278)   473.0  ...         0           0

[3234 rows x 18 columns]

In [ ]:
lscp_pop_and_bike.columns

Index(['좌표', '대여수', '반납수', '총 이용횟수', '스테이션', '주거인구', '버스_승하차수', '지하철_승하차수',
       '위도', '경도', 'DN_avg', 'Road_yes', 'Space_count', 'Culture_count',
       'Sport_count', 'KINTEX', 'Hosu_yes', 'Park_count'],
      dtype='object')

In [ ]:
y = lscp_pop_and_bike[['총 이용횟수']]
X = lscp_pop_and_bike[['주거인구', '버스_승하차수', '지하철_승하차수', 'DN_avg', 'Road_yes', 'Space_count', 'Culture_count',
       'Sport_count', 'KINTEX', 'Hosu_yes', 'Park_count']]

X.shape, y.shape

((3234, 11), (3234, 1))

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 42, test_size = 0.1)

X_train.shape, X_test.shape, y_train.shape

((2910, 11), (324, 11), (2910, 1))

In [ ]:
numerical_columns = ['주거인구', '버스_승하차수', '지하철_승하차수',  'DN_avg', 'Space_count', 'Culture_count',
       'Sport_count', 'Park_count']

In [ ]:
from sklearn.preprocessing import StandardScaler
std_scaler = StandardScaler()

std_scaler.fit(X_train[numerical_columns])

std_scaler.transform(X_train[numerical_columns])
std_scaler.transform(X_test[numerical_columns])

array([[ 0.78594449, -0.71582524, -0.33583384, ..., -0.27128377,
        -0.39681393,  2.16469075],
       [-0.05063649, -0.28870097, -0.33583384, ..., -0.27128377,
        -0.39681393, -0.83423811],
       [ 0.18896449, -0.52494794, -0.33583384, ..., -0.27128377,
        -0.39681393,  0.66522632],
       ...,
       [ 0.18515753,  1.62514181, -0.33583384, ...,  4.85492249,
        -0.39681393, -0.83423811],
       [-0.085613  , -0.51069125, -0.33583384, ...,  1.43745165,
         2.37231928,  0.66522632],
       [-1.37236782, -0.59580792, -0.33583384, ..., -0.27128377,
        -0.39681393,  0.66522632]])

In [ ]:
import xgboost as xgb

xgb_model = xgb.XGBRegressor(n_estimators=500, 
                              learning_rate = 0.1, 
                              max_depth = 3, objective = 'reg:squarederror').fit(X_train, y_train)

In [ ]:
print('train score : {}'.format(xgb_model.score(X_train, y_train)))
print('test score : {}'.format(xgb_model.score(X_test, y_test)))

train score : 0.8452937932073423
test score : 0.7753600391380695


In [ ]:
feature_important = [ X_train.columns[i] for i in np.argsort(xgb_model.feature_importances_)[::-1]]
feature_important

['Hosu_yes',
 '지하철_승하차수',
 'Road_yes',
 'Park_count',
 '버스_승하차수',
 'Space_count',
 'DN_avg',
 'Culture_count',
 '주거인구',
 'Sport_count',
 'KINTEX']

## 도로명 주소 추가 

In [ ]:
lscp_all = pd.read_csv('/content/drive/My Drive/Compas/compas/이소연 자료/lscp_all_300_도로명추가.csv')
lscp_all

좌표     대여수  ...  CD_90002  CD_05502_식물원
0      (37.59052639593674, 126.88041634904563)     0.0  ...         0             0
1     (37.590546726423185, 126.88154829019997)     0.0  ...         0             0
2      (37.59142713034578, 126.88039079257342)     0.0  ...         0             0
3      (37.59144746148929, 126.88152274735107)     0.0  ...         0             0
4      (37.59146778178655, 126.88265470326604)     0.0  ...         0             0
...                                        ...     ...  ...       ...           ...
3229   (37.70445091519225, 126.75467703178417)  6093.0  ...         0             0
3230  (37.704472506609626, 126.75581060819373)  6093.0  ...         0             0
3231    (37.70466633943072, 126.7660128502553)   473.0  ...         0             0
3232   (37.70468782197291, 126.76714643873707)   473.0  ...         0             0
3233   (37.70470929362739, 126.76828002842278)   473.0  ...         0             0

[3234 rows x 239 columns]

In [ ]:
y = lscp_all[['총 이용횟수']]
X = lscp_all.drop(['좌표', '대여수', '반납수', '총 이용횟수', '스테이션', '유동인구','위도', '경도'], axis =1)

X.shape, y.shape

((3234, 231), (3234, 1))

In [ ]:
X.columns

Index(['주거인구', '버스_승하차수', '지하철_승하차수', 'DN_avg', 'Road_yes', 'Space_count',
       'Culture_count', 'Sport_count', 'KINTEX', 'Hosu_yes',
       ...
       'CD_04021_세탁소', 'CD_09011', 'CD_20002_세차장', 'CD_06201', 'CD_17105',
       'CD_08699', 'CD_03109_공공도서관', 'CD_27999_기타관광휴게시설', 'CD_90002',
       'CD_05502_식물원'],
      dtype='object', length=231)

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 42, test_size = 0.1)

X_train.shape, X_test.shape, y_train.shape

((2910, 231), (324, 231), (2910, 1))

In [ ]:
numerical_columns = X.columns.drop(['Road_yes','KINTEX', 'Hosu_yes'])
numerical_columns.shape

(228,)

In [ ]:
from sklearn.preprocessing import StandardScaler
std_scaler = StandardScaler()

std_scaler.fit(X_train[numerical_columns])

std_scaler.transform(X_train[numerical_columns])
std_scaler.transform(X_test[numerical_columns])

array([[ 0.78594449, -0.71582524, -0.33583384, ...,  0.        ,
        -0.1308697 , -0.03212463],
       [-0.05063649, -0.28870097, -0.33583384, ...,  0.        ,
        -0.1308697 , -0.03212463],
       [ 0.18896449, -0.52494794, -0.33583384, ...,  0.        ,
        -0.1308697 , -0.03212463],
       ...,
       [ 0.18515753,  1.62514181, -0.33583384, ...,  0.        ,
        -0.1308697 , -0.03212463],
       [-0.085613  , -0.51069125, -0.33583384, ...,  0.        ,
        -0.1308697 , -0.03212463],
       [-1.37236782, -0.59580792, -0.33583384, ...,  0.        ,
        -0.1308697 , -0.03212463]])

In [ ]:
import xgboost as xgb

xgb_model = xgb.XGBRegressor(n_estimators=500, 
                              learning_rate = 0.1, 
                              max_depth = 3, objective = 'reg:squarederror').fit(X_train, y_train)

print('train score : {}'.format(xgb_model.score(X_train, y_train)))
print('test score : {}'.format(xgb_model.score(X_test, y_test)))

feature_important = [ X_train.columns[i] for i in np.argsort(xgb_model.feature_importances_)[::-1]]
feature_important

train score : 0.9399494966436084
test score : 0.900054126433578


['CD_10299_기타교육원',
 'CD_90001',
 'Road_yes',
 'CD_04402_사무소',
 'CD_07102_백화점',
 'Hosu_yes',
 '지하철_승하차수',
 'CD_10199_기타학교',
 'CD_02003_다세대주택',
 'CD_04102_체력단련장',
 'CD_17007',
 'CD_02006_복리시설',
 'CD_03012_공중화장실',
 'CD_05999_기타문화및집회시설',
 'CD_03004',
 'CD_16002_유흥주점',
 'CD_02005_부대시설',
 'CD_05199_기타공연장',
 'CD_02007_기숙사',
 'CD_15009',
 'CD_14999',
 'CD_08003',
 'CD_06203',
 'CD_03101',
 'DN_avg',
 'CD_03999_기타제1종근린생활시설',
 'CD_04006_수리점',
 'CD_04201_교회',
 'CD_04018_자동차영업소',
 'CD_11201_노인복지시설',
 'Culture_count',
 'Park_count',
 'CD_04202_성당',
 'CD_04999_기타제2종근생활시설',
 'CD_05501_동물원',
 'CD_04004_서점(1종근.생미해당)',
 'CD_08103',
 'CD_10204',
 'CD_02001_아파트',
 'CD_08102',
 'CD_06204',
 'CD_04499_기타사무소',
 'CD_21999_기타동식물관련시설',
 'Space_count',
 '주거인구',
 'CD_02002_연립주택',
 'CD_01002_다중주택',
 'CD_01001_단독주택',
 'CD_03001_소매점',
 'CD_16001_단란주점',
 'CD_11102_영유아보육시설',
 'CD_08601',
 'CD_06310',
 'CD_05299_기타집회장',
 'CD_11199_기타아동관련시설',
 'CD_03021_마을회관',
 'CD_01003_다가구주택',
 'CD_04105_당구장',
 'CD_08005',
 'CD_07199_

총 대여

In [ ]:
lscp_all

좌표     대여수  ...  CD_90002  CD_05502
0      (37.59052639593674, 126.88041634904563)     0.0  ...         0         0
1     (37.590546726423185, 126.88154829019997)     0.0  ...         0         0
2      (37.59142713034578, 126.88039079257342)     0.0  ...         0         0
3      (37.59144746148929, 126.88152274735107)     0.0  ...         0         0
4      (37.59146778178655, 126.88265470326604)     0.0  ...         0         0
...                                        ...     ...  ...       ...       ...
3229   (37.70445091519225, 126.75467703178417)  6093.0  ...         0         0
3230  (37.704472506609626, 126.75581060819373)  6093.0  ...         0         0
3231    (37.70466633943072, 126.7660128502553)   473.0  ...         0         0
3232   (37.70468782197291, 126.76714643873707)   473.0  ...         0         0
3233   (37.70470929362739, 126.76828002842278)   473.0  ...         0         0

[3234 rows x 239 columns]

In [ ]:
y = lscp_all[['대여수']]
X = lscp_all.drop(['좌표', '대여수', '반납수', '총 이용횟수','유동인구', '스테이션', '위도', '경도'], axis =1)

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 42, test_size = 0.1)

print(X_train.shape, X_test.shape, y_train.shape)

numerical_columns = X.columns.drop(['Road_yes','KINTEX', 'Hosu_yes'])
print(numerical_columns.shape)

from sklearn.preprocessing import StandardScaler
std_scaler = StandardScaler()

std_scaler.fit(X_train[numerical_columns])

std_scaler.transform(X_train[numerical_columns])
std_scaler.transform(X_test[numerical_columns])

(2910, 231) (324, 231) (2910, 1)
(228,)


array([[ 0.78594449, -0.71582524, -0.33583384, ...,  0.        ,
        -0.1308697 , -0.03212463],
       [-0.05063649, -0.28870097, -0.33583384, ...,  0.        ,
        -0.1308697 , -0.03212463],
       [ 0.18896449, -0.52494794, -0.33583384, ...,  0.        ,
        -0.1308697 , -0.03212463],
       ...,
       [ 0.18515753,  1.62514181, -0.33583384, ...,  0.        ,
        -0.1308697 , -0.03212463],
       [-0.085613  , -0.51069125, -0.33583384, ...,  0.        ,
        -0.1308697 , -0.03212463],
       [-1.37236782, -0.59580792, -0.33583384, ...,  0.        ,
        -0.1308697 , -0.03212463]])

In [ ]:
import xgboost as xgb

xgb_model = xgb.XGBRegressor(n_estimators=500, 
                              learning_rate = 0.1, 
                              max_depth = 3, objective = 'reg:squarederror').fit(X_train, y_train)

print('train score : {}'.format(xgb_model.score(X_train, y_train)))
print('test score : {}'.format(xgb_model.score(X_test, y_test)))

train score : 0.9374852137872844
test score : 0.8911773045215063


In [ ]:
feature_important = [ X_train.columns[i] for i in np.argsort(xgb_model.feature_importances_)[::-1]]
feature_important

['Road_yes',
 'CD_10299_기타교육원',
 'CD_90001',
 'CD_04402_사무소',
 'Hosu_yes',
 '지하철_승하차수',
 'CD_02003_다세대주택',
 'CD_03012_공중화장실',
 'CD_10199_기타학교',
 'CD_16002_유흥주점',
 'CD_03101',
 'CD_17007',
 'CD_05999_기타문화및집회시설',
 'CD_04102_체력단련장',
 'CD_02006_복리시설',
 'CD_05501_동물원',
 'CD_15009',
 'CD_02005_부대시설',
 'CD_04202_성당',
 'CD_14999',
 'Park_count',
 'CD_02007_기숙사',
 'CD_04201_교회',
 'CD_06203',
 'CD_08601',
 'CD_11201_노인복지시설',
 'CD_03999_기타제1종근린생활시설',
 'DN_avg',
 'CD_10204',
 'CD_05299_기타집회장',
 'CD_08202',
 'CD_04006_수리점',
 'CD_02001_아파트',
 'CD_08103',
 'CD_04399_기타공연장',
 'CD_01002_다중주택',
 'CD_04018_자동차영업소',
 'CD_07199_기타소매시장',
 'CD_04105_당구장',
 'CD_04004_서점(1종근.생미해당)',
 'CD_08003',
 'CD_06305',
 'CD_21999_기타동식물관련시설',
 'CD_01001_단독주택',
 'Space_count',
 'CD_02002_연립주택',
 'CD_11199_기타아동관련시설',
 'CD_05199_기타공연장',
 'CD_06999_기타종교시설',
 'CD_06310',
 'CD_04999_기타제2종근생활시설',
 'CD_08203',
 'CD_08300',
 'CD_08102',
 'CD_08400',
 'CD_14001',
 '주거인구',
 'CD_07101_시장',
 'CD_04499_기타사무소',
 'CD_03109_공공도서관',
 'CD_1

In [ ]:
y = lscp_all[['반납수']]
X = lscp_all.drop(['좌표', '대여수', '반납수', '유동인구','총 이용횟수', '스테이션', '위도', '경도'], axis =1)

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 42, test_size = 0.1)

print(X_train.shape, X_test.shape, y_train.shape)

numerical_columns = X.columns.drop(['Road_yes','KINTEX', 'Hosu_yes'])
print(numerical_columns.shape)

from sklearn.preprocessing import StandardScaler
std_scaler = StandardScaler()

std_scaler.fit(X_train[numerical_columns])

std_scaler.transform(X_train[numerical_columns])
std_scaler.transform(X_test[numerical_columns])

(2910, 231) (324, 231) (2910, 1)
(228,)


array([[ 0.78594449, -0.71582524, -0.33583384, ...,  0.        ,
        -0.1308697 , -0.03212463],
       [-0.05063649, -0.28870097, -0.33583384, ...,  0.        ,
        -0.1308697 , -0.03212463],
       [ 0.18896449, -0.52494794, -0.33583384, ...,  0.        ,
        -0.1308697 , -0.03212463],
       ...,
       [ 0.18515753,  1.62514181, -0.33583384, ...,  0.        ,
        -0.1308697 , -0.03212463],
       [-0.085613  , -0.51069125, -0.33583384, ...,  0.        ,
        -0.1308697 , -0.03212463],
       [-1.37236782, -0.59580792, -0.33583384, ...,  0.        ,
        -0.1308697 , -0.03212463]])

In [ ]:
import xgboost as xgb

xgb_model = xgb.XGBRegressor(n_estimators=500, 
                              learning_rate = 0.1, 
                              max_depth = 3, objective = 'reg:squarederror').fit(X_train, y_train)

print('train score : {}'.format(xgb_model.score(X_train, y_train)))
print('test score : {}'.format(xgb_model.score(X_test, y_test)))

train score : 0.9429346450323882
test score : 0.9045979644449195


In [ ]:
feature_important = [ X_train.columns[i] for i in np.argsort(xgb_model.feature_importances_)[::-1]]
feature_important

['CD_10299_기타교육원',
 'CD_90001',
 'Hosu_yes',
 'CD_04402_사무소',
 '지하철_승하차수',
 'Road_yes',
 'CD_05102_음악당',
 'CD_02006_복리시설',
 'CD_10199_기타학교',
 'CD_04102_체력단련장',
 'CD_02003_다세대주택',
 'CD_05999_기타문화및집회시설',
 'CD_03012_공중화장실',
 'CD_16002_유흥주점',
 'CD_15009',
 'CD_17007',
 'CD_02005_부대시설',
 'CD_04499_기타사무소',
 'Park_count',
 'CD_03101',
 'CD_08999_기타운수시설',
 'CD_02007_기숙사',
 'CD_11201_노인복지시설',
 'CD_04202_성당',
 'CD_03004',
 'CD_06203',
 'CD_14999',
 'CD_08003',
 'CD_08601',
 'DN_avg',
 'CD_02002_연립주택',
 'CD_04999_기타제2종근생활시설',
 'CD_03999_기타제1종근린생활시설',
 'CD_07199_기타소매시장',
 'CD_04006_수리점',
 'CD_06305',
 'CD_04018_자동차영업소',
 'CD_04201_교회',
 'Culture_count',
 'CD_01002_다중주택',
 'CD_04004_서점(1종근.생미해당)',
 'CD_08103',
 'CD_05299_기타집회장',
 '주거인구',
 'CD_05199_기타공연장',
 'CD_01003_다가구주택',
 'CD_08400',
 'CD_11199_기타아동관련시설',
 'CD_08202',
 'CD_03100_공공시설',
 'CD_02001_아파트',
 'CD_06202',
 'CD_08001_여객자동차터미널',
 'CD_01001_단독주택',
 'CD_05101',
 'CD_14001',
 'CD_05501_동물원',
 'CD_16001_단란주점',
 'CD_08101',
 'CD_08300',
 'CD

In [ ]:
X

주거인구  버스_승하차수  지하철_승하차수  ...  CD_27999  CD_90002  CD_05502
0       74.0      0.0       0.0  ...         0         0         0
1       36.0      0.0       0.0  ...         0         0         0
2      135.0      0.0       0.0  ...         0         0         0
3       82.0      0.0       0.0  ...         0         0         0
4       36.0      0.0       0.0  ...         0         0         0
...      ...      ...       ...  ...       ...       ...       ...
3229  3562.0   5665.0       0.0  ...         0         0         0
3230  2661.0   3486.0       0.0  ...         0         0         0
3231  7713.0  21185.0       0.0  ...         0         0         0
3232  6526.0  21185.0       0.0  ...         0         0         0
3233  5898.0  21185.0       0.0  ...         0         0         0

[3234 rows x 232 columns]